# Generated by Django 4.2.6 on 2023-12-12 06:40

from django.db import migrations, models
import userposts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500)),
                ('media_file', models.FileField(blank=True, null=True, upload_to=userposts.models.upload_to)),
            ],
        ),
    ]
