# Generated by Django 4.2.6 on 2024-03-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0016_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='repost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userposts.repost'),
        ),
        migrations.AddField(
            model_name='likes',
            name='repost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userposts.repost'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userposts.userposts'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userposts.userposts'),
        ),
    ]
