# Generated by Django 4.2.6 on 2023-12-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersofweb', '0004_rename_firstname_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='def.webp', null=True, upload_to='profile_pics'),
        ),
    ]
