# Generated by Django 4.2.6 on 2024-02-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersofweb', '0010_userconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconnection',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userconnection',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
    ]
